### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by extesy** [Yiling-J/theine#14]
Here is the minimal test case:
```python
from theine import Cache

cache: Cache = Cache(policy="tlfu", size=10000)

def test1() -> None:
    print(len(cache))
    cache.clear()

def test2() -> None:
    print(len(cache))
    cache.clear()
```
I am running this test file using pytest. Second test fails with `OverflowError: cannot fit 'int' into an index-sized integer` error. If I remove `cache.clear()` then it works. If I change the policy to "clockpro" then it also works.

Environment: MacOS 13.5.1, python 3.8.16.

**Comment by Yiling-J** [comment]
@extesy please upgrade theine-core to v0.4.2 and try again 🙏

**Comment by extesy** [comment]
@Yiling-J That fixed the problem. Thank you for a quick response!
