### ISSUE TITLE
Documentation: background threads behavior

### ISSUE THREAD

**Issue by econtal** [Yiling-J/theine#15]
In a django backend, we had one of the request that (wrongly) triggered the instantiation of a new `Cache` instance, which was then garbage collected immediately after the request finished.

With this pattern, we noticed the CPU usage of our backend to increase linearly with the number of past requests served. We ultimately traced it down to this erroneous creation of `Cache` instances.

I guess it is starting a new background thread for each instance, and these threads are not killed with garbage collection, hence resulting in millions of threads after some time.

The `theine` library has multiple interfaces. Could you document which pattern starts new threads in the background? Would it affect the `@Memoize` decorator or the django adapter? For instance if inside a request handling we have a dynamic function with `@Memoize`, wouldn't that also instantiate a new cache at each request without ever killing background threads?

**Comment by Yiling-J** [comment]
@econtal Add some details in [Readme](https://github.com/Yiling-J/theine#api), please take a look

**Comment by econtal** [comment]
awesome, very clear!
