### ISSUE TITLE
Configure PyPi license

### ISSUE THREAD

**Issue by k0t3n** [Yiling-J/theine#24]
PYPI has no license configured (https://pypi.org/project/theine/). Some license checkers rely on that info and cannot get access to the `LICENSE` file, I would be very grateful if you add the BSD 3-Clause License to the PyPi package info (the same as Django https://pypi.org/project/Django/ or any other packages have).
Thanks.

**Comment by k0t3n** [comment]
Same for `theine-core`.

**Comment by Yiling-J** [comment]
@k0t3n Thank you for pointing that out. I have added the BSD 3-Clause License to PYPI. Please take a look.

**Comment by k0t3n** [comment]
@Yiling-J looks great, thank you.
